---
- hosts: audit
  become: true
  tasks:
   - name: remove deprecated or insecure package
     yum:
       name: "*"
       state: "latest"
       exclude: mysql*,mongo*,maria*,nginx*,java*,tz-data*,tz-java*,httpd*,mod_ssl*,filebeat*,jdk*,wazuh*,suricata*,ipa-client*,clamav*,zabbix*,td-agent-bit*,percona*,clamd*,redis*

   - name: restart system
     shell: "sleep 5 && reboot"
     async: 1
     poll: 0

   - name: wait for 10 seconds
     pause:
      seconds: 10

   - name: wait for the system to reboot
     wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 60
